#!/usr/bin/env python3
"""Publish the HTML generated by scripts/publish_daily_report.py.

OpenClaw instances commonly run a publish-server bound to :3000 with root:
  /home/node/.openclaw/workspace/published

This legacy wrapper no longer generates report data. Use
scripts/publish_daily_report.py as the single data/HTML entry point, then pass
the generated HTML path here.

So it becomes available at:
  https://openclaw-pub-<instance>.imlgz.com/portfolio-management/

Default is to copy reports/latest.html.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_HTML = REPO_ROOT / "reports" / "latest.html"
PUBLISHED_ROOT = Path("/home/node/.openclaw/workspace/published")
TARGET_DIR = PUBLISHED_ROOT / "portfolio-management"
TARGET_HTML = TARGET_DIR / "index.html"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Copy an already generated daily report HTML into OpenClaw publish root.")
    parser.add_argument("--source", default=str(DEFAULT_SOURCE_HTML), help="HTML file generated by scripts/publish_daily_report.py.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    source = Path(args.source)
    if not source.exists():
        raise RuntimeError(
            f"Expected generated HTML at {source}; run scripts/publish_daily_report.py first."
        )

    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, TARGET_HTML)
    print(str(TARGET_HTML))


if __name__ == "__main__":
    main()
